#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - uninstall                              Copyright(c) 2013 cPanel, Inc.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use Cpanel::Version ();

unlink("/usr/local/cpanel/whostmgr/docroot/cgi/addon_securityadvisor.cgi");
system "/bin/rm","-rf","--","/var/cpanel/addons/securityadvisor/";

print "cPanel Security Advisor uninstalled into WHM.\n";

exit(0);
